name: Continuous Deployment

on:
  push:
    branches:
      - main
      - prod
      - dev

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    name: Deploy Backend Services (Java)

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build Backend Services
      run: |
        cd inventory-service && ./gradlew clean build
        cd ../user-auth-service && ./gradlew clean build
        cd ../api-gateway && ./gradlew clean build
        cd ../advertisement-service && ./gradlew clean build

    - name: Deploy Backend to Production
      if: github.ref == 'refs/heads/prod'
      run: echo "Deploying backend to production..."

    - name: Deploy Backend to Staging
      if: github.ref == 'refs/heads/dev'
      run: echo "Deploying backend to staging..."

  deploy-frontend:
    needs: deploy-backend  # Ensure backend deployment completes first
    runs-on: ubuntu-latest
    name: Deploy Frontend (Angular)

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build Frontend
      run: npm run build
      working-directory: ./car-inventory-portal

    - name: Deploy Frontend to Production
      if: github.ref == 'refs/heads/prod'
      run: echo "Deploying frontend to production..."

    - name: Deploy Frontend to Staging
      if: github.ref == 'refs/heads/dev'
      run: echo "Deploying frontend to staging..."
