name: Continuous Deployment
on:
  push:
    branches: [main, prod, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
    - uses: actions/checkout@v3
    
    # Backend Setup & Build
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Build Backend
      run: |
        chmod +x */gradlew
        for service in inventory-service user-auth-service api-gateway advertisement-service; do
          cd $service && ./gradlew clean build --no-daemon && cd ..
        done
    
    # Frontend Setup & Build
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Build Frontend
      working-directory: ./car-inventory-portal
      run: |
        npm ci
        npm run build
    
    - name: Deploy
      run: |
        if [[ $GITHUB_REF == 'refs/heads/prod' ]]; then
          echo "Deploying to production..."
          # Add production deployment commands
        elif [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
          echo "Deploying to staging..."
          # Add staging deployment commands
        fi
