name: Continuous Deployment
on:
  push:
    branches: [main, prod, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
    - uses: actions/checkout@v3
    
    # Backend Setup & Build
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Build Backend
      run: |
        chmod +x inventory-service/gradlew
        cd inventory-service && ./gradlew clean build --no-daemon
    
    # Improved Frontend Setup & Build
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'car-inventory-portal/package-lock.json'
    
    - name: Install Frontend Dependencies
      working-directory: ./car-inventory-portal
      run: |
        npm clean-install   # Uses package-lock.json exactly as-is
        npm ci              # Faster alternative to 'npm install'
    
    - name: Build Frontend
      working-directory: ./car-inventory-portal
      run: npm run build
    
    - name: Deploy
      run: |
        if [[ $GITHUB_REF == 'refs/heads/prod' ]]; then
          echo "Deploying to production environment..."
        elif [[ $GITHUB_REF == 'refs/heads/main' ]]; then
          echo "Deploying to staging environment..."
        elif [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
          echo "Deploying to development environment..."
        fi
